check script

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -33,29 +33,29 @@ jobs:
           ls
           cd Conformance-Gateway/spring-boot && docker-compose -f docker-compose.yml up -d -V --build
 
-      - name: Fetch Backend Status
-        run: |
-          sleep 10
-          status=$(curl -s http://localhost:8080/actuator/health | jq -r '.status')
-          retries=12
-
-          while [[ "$status" != "UP" ]] && [[ $retries -gt 0 ]]; do
-            echo "Status is '$status' - waiting 5 secs ($retries retries left)"
-            sleep 5
-            retries=$((retries - 1))
-            status=$(curl -s http://localhost:8080/actuator/health | jq -r '.status')
-          done
-
-          echo "Final status is '$status'"
-          if [[ "$status" != "UP" ]]; then
-            curl -v http://localhost:8080/actuator/health || :
-            exit 1
-          fi
-
-          echo "::set-output name=STATUS::$status"
-        id: healthcheck
-
-      - name: Confirm microservice status
-        if: ${{ steps.healthcheck.outputs.STATUS == 'UP' }}
-        run: |
-          echo "The Conformance-Gateway service is UP."
+#      - name: Fetch Backend Status
+#        run: |
+#          sleep 10
+#          status=$(curl -s http://localhost:8080/actuator/health | jq -r '.status')
+#          retries=12
+#
+#          while [[ "$status" != "UP" ]] && [[ $retries -gt 0 ]]; do
+#            echo "Status is '$status' - waiting 5 secs ($retries retries left)"
+#            sleep 5
+#            retries=$((retries - 1))
+#            status=$(curl -s http://localhost:8080/actuator/health | jq -r '.status')
+#          done
+#
+#          echo "Final status is '$status'"
+#          if [[ "$status" != "UP" ]]; then
+#            curl -v http://localhost:8080/actuator/health || :
+#            exit 1
+#          fi
+#
+#          echo "::set-output name=STATUS::$status"
+#        id: healthcheck
+#
+#      - name: Confirm microservice status
+#        if: ${{ steps.healthcheck.outputs.STATUS == 'UP' }}
+#        run: |
+#          echo "The Conformance-Gateway service is UP."
